### ISSUE TITLE
Can't compile because of "_requestedState"

### ISSUE THREAD

**Issue by RyutoSetsujin** [Sword352/FNF-EternalEngine#4]
### Describe the issue here.

Title should explain itself. I followed all the compilation instructions, and even installed fixel-tools and yaml since those aren't included in setup.bat for some reason.

### Command Prompt/Terminal logs (if existing)

```bash
source/eternal/core/crash/FNFGame.hx:59: characters 9-24 : Unknown identifier : _requestedState
```

### What target were you compiling to?

Windows

### Did you edit anything?

No

**Comment by Sword352** [comment]
The master branch is pretty outdated.
You can fix it by replacing that line with:
```haxe
_nextState = CrashScreen.new.bind(func);
```

I wouldn't recommend making anything with the engine as of now, if you just wanna experiment with things I'd recommend using the dev branch.

**Comment by moxie-coder** [comment]
yeah the master branch is pretty much outdated af, I would use the dev one since that’s what is getting most updates

**Comment by RyutoSetsujin** [comment]
Ah, thank you. I'll try that branch.
