### ISSUE TITLE
Error: Null Object Reference

### ISSUE THREAD

**Issue by RyutoSetsujin** [Sword352/FNF-EternalEngine#5]
### Describe the bug here.

I finally started using the dev branch, and it actually compiled for once. However, I encounter an error whenever I try to play _any_ song.
Attached is my crash log.
[FNF-EE_2024-04-30_19'40'04.txt](https://github.com/Sword352/FNF-EternalEngine/files/15172680/FNF-EE_2024-04-30_19.40.04.txt)

Screenshot of the error:
https://ryuto.dumbfuck.agency/📸/nj9cbixv.png

### Are you modding a build from source or from mods folder?

Source

### What target were you compiling to?

Windows

### If you use source, did you edit anything?

No.

**Comment by Sword352** [comment]
Was it happening after the countdown? I got a similar issue and managed to fix it recently

**Comment by RyutoSetsujin** [comment]
Yes, it was after the countdown. I'll try the latest commit and see what happens.

**Comment by RyutoSetsujin** [comment]
That worked! Thank you!
